name: Deploy Casino Website

on:
  push:
    branches:
      - main

jobs:
  frontend-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          cd frontend
          npm install

      - name: Deploy to Vercel
        run: |
          npm install -g vercel
          vercel --token ${{ secrets.VERCEL_TOKEN }} --prod

  backend-deploy:
    runs-on: ubuntu-latest
    needs: frontend-deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to AWS EC2
        env:
          SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          SSH_USER: "ubuntu"
          SSH_HOST: ${{ secrets.EC2_HOST }}
        run: |
          echo "$SSH_KEY" > deploy_key.pem
          chmod 600 deploy_key.pem
          ssh -i deploy_key.pem $SSH_USER@$SSH_HOST << 'EOF'
            cd /home/ubuntu/casino-backend
            git pull origin main
            npm install
            pm2 restart all
          EOF

